### ISSUE TITLE
Bump version of docker-build-push Action

### ISSUE THREAD

**Issue by phenixblue** [tmobile/magtape#40]
**What would you like to be added**:

Move to using v2 of docker-build-push Action

**Why is this needed**:

v1 of the docker-build-push action has been deprecated, need to move to v2

Original deprecation shown in this CI output: https://github.com/tmobile/magtape/runs/1121343080?check_suite_focus=true#step:6:1

**Comment by phenixblue** [comment]
Looks like there are some big changes with v2. The move is towards using Moby's buildx and splitting existing functionality into multiple actions (from the quick glance I gave it today).

**Comment by Shahar-Levy** [comment]
@phenixblue Currently, magtape uses github secrets to push release tags that others don't have access to. Some options we can try 1) Set up a tmobile/testing-magtape (or similar) to push images to for testing. 2) Change the code to use a different throwaway registry (and dockerhub secrets) and change them back 3) Push junk to tmobile/magtape and attempt to cleanup. The ci-image-build action also runs on published releases (rather than pushes). How have you been testing to see that changes to this work?

**Comment by Shahar-Levy** [comment]
After conversation with @phenixblue, we will move forward with option 2 and make a test release in tmobile/magtape to confirm this works after merging.

In v2 of docker-build-push, simple authentication is not required for docker build steps. We can remove the simple auth from the e2e-checks step for ci. This would allow e2e checks to run on all pull requests and pushes, regardless of whether you are working from the tmobile/magtape github repository or your own fork. @phenixblue, what are your thoughts on running e2e checks on every PR/Push, rather than just PRs to tmobile/magtape? Currently e2e checks only run on tmobile/magtape PRs and pushes.

**Comment by phenixblue** [comment]
I think it's fine to remove the auth and the repo conditional portions for the e2e checks.

**Comment by ilrudie** [comment]
> I think it's fine to remove the auth and the repo conditional portions for the e2e checks.

Thanks
